export enum RoleCodeEnum {
  CREATE_CONTACT = 'CREATE_CONTACT',
  UPDATE_CONTACT = 'UPDATE_CONTACT',
  VIEW_CONTACT = 'VIEW_CONTACT',
  DELETE_CONTACT = 'DELETE_CONTACT',
  CHANGE_STATUS_CONTACT = 'CHANGE_STATUS_CONTACT',
  ALL_PERMISSION_CONTACT = 'ALL_PERMISSION_CONTACT',
  TEST = 'TEST_ROLE',
}
